### ISSUE TITLE
How to run Pylance

### ISSUE THREAD

**Issue by vpeopleonatank** [kuator/nvim#1]
I see in your lsp config, you use Pylance as python lsp. But since 10.2020, Pylance can't be run by `node` command. Can you share me trick to run pylance with `node`?

**Comment by kuator** [comment]
Unfortunately, there is no trick, I'm just sticking to the old version

**Comment by kuator** [comment]
@vpeopleonatank 
![image](https://user-images.githubusercontent.com/25168308/113486239-8aa4d280-94d3-11eb-9c49-5d4cd6338e8a.png)

**Comment by vpeopleonatank** [comment]
Have you modified some code? I tried to run again but it didn't work
![image](https://user-images.githubusercontent.com/30976876/113493867-97deb300-950d-11eb-9055-daad2e31d234.png)

**Comment by kuator** [comment]
> Have you modified some code? I tried to run again but it didn't work
> ![image](https://user-images.githubusercontent.com/30976876/113493867-97deb300-950d-11eb-9055-daad2e31d234.png)

Here you go, I updated my plugin: https://github.com/kuator/pylance.nvim, hope it helps! 
Spent my weekend reading obfuscated javascript, I hate microsoft.
